version: "3"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./expo_app/
        target: /home/local/
    stdin_open: true
    tty: true
    ports:
      - 8081:8081
      - 9005:9005
    # command: >
    #   sh -c "npm start -- --tunnel"
