name: lock issue conversation on open
on:
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  lock_issue:
    runs-on: ubuntu-latest

    steps:
      - name: lock issue from script
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.lock({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
