name: Update README with Closed Issues

on:
  issues:
    types:
      - closed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch open issues and update README
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Fetch open and closed issues
            const open_issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });
            const closed_issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });

            // Generate markdown for issues
            let openIssueSection = '## Open Issues\n';
            open_issues.slice(0, 10).forEach(issue => {
              openIssueSection += `- [${issue.title}](${issue.html_url})`;
            })
            let closedIssueSection = '## Close Issues\n';
            closed_issues.slice(0, 10).forEach(issue => {
              closedIssueSection += `- [${issue.title}](${issue.html_url})`;
            })

            // Read the current README
            let readme = fs.readFileSync('README.md', 'utf8');

            // Check if the issues section already exists
            const openIssueRegex = /## Open Issues[\s\S]*?(?=\n## |$)/;
            const closedIssueRegex = /## Closed Issues[\s\S]*?(?=\n## |$)/;
            if (openIssueRegex.test(readme)) {
              readme = readme.replace(openIssueRegex, openIssueSection);
            } else {
              readme += '\n\n' + openIssueSection;
            }
            if (closedIssueRegex.test(readme)) {
              readme = readme.replace(closedIssueRegex, closedIssueSection);
            } else {
              readme += '\n\n' + closedIssueSection;
            }

            // Write the updated README
            fs.writeFileSync('README.md', readme);

            // Commit changes
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
              message: 'Update README with open and closed issue sections',
              content: Buffer.from(readme).toString('base64'),
              sha: (await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md'
              })).data.sha
            });
