name: Update README with Closed Issues

on:
  issues:
    types:
      - closed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch closed issues and update README
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Fetch closed issues
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });

            // Generate markdown for issues
            let issuesMarkdown = '## Closed Issues\n\n';
            issues.slice(0, 10).forEach(issue => {  // Limit to 10 most recent issues
              issuesMarkdown += `- [${issue.title}](${issue.html_url}) - closed on ${new Date(issue.closed_at).toDateString()}\n`;
            });

            // Read the current README
            let readme = fs.readFileSync('README.md', 'utf8');

            // Check if the issues section already exists
            const issuesSectionRegex = /## Closed Issues[\s\S]*?(?=\n## |$)/;
            if (issuesSectionRegex.test(readme)) {
              // Replace the existing section
              readme = readme.replace(issuesSectionRegex, issuesMarkdown);
            } else {
              // Append the new section
              readme += '\n\n' + issuesMarkdown;
            }

            // Write the updated README
            fs.writeFileSync('README.md', readme);

            // Commit changes
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
              message: 'Update README with closed issues',
              content: Buffer.from(readme).toString('base64'),
              sha: (await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md'
              })).data.sha
            });

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update README with closed issues" || exit 0
          git push
